import { ApiCategory } from '@shared/models/api-docs.model';
import {
  AUTHORIZATION_HEADER,
  BAD_REQUEST_EXCEPTION,
  EMAIL_IN_USE_EXCEPTION,
  FORBIDDEN_EXCEPTION, INTERNAL_SERVER_EXCEPTION, INVALID_CREDENTIALS_EXCEPTION, NOT_FOUND_EXCEPTION,
  RATELIMIT_EXCEPTION,
  STANDARD_EXCEPTIONS, UNAUTHORIZED_EXCEPTION,
  USERNAME_IN_USE_EXCEPTION
} from './default-responses';

export const API_STRUCTURE: ApiCategory[] = [
  // Auth
  {
    name: 'Auth',
    basePath: 'http://localhost:8080/api/v1/auth',
    description: 'Authentication endpoint',
    endpoints: [
      {
        id: 'auth-signup',
        path: '/signup',
        title: 'Create account',
        method: 'POST',
        description: 'Create a new account. \n\n You will still need to log in after the signup request',
        bodyParams: [
          { name: 'username', type: 'string', description: 'Your username', exampleValue: 'star123best@gmail.com', required: true },
          { name: 'password', type: 'string', description: 'Your password', exampleValue: '##########', required: true},
          { name: 'email', type: 'string', description: 'Your email', exampleValue: 'star123best@gmail.com', required: true },
          { name: 'displayName', type: 'string', description: 'A display name', exampleValue: 'Star', required: false },
        ],
        responses: [
          { code: 200, title: 'Success', description: 'Successful login', exampleJson: '{\n' +
              '    "createdAt": 1774996384,\n' +
              '    "displayName": "Star",\n' +
              '    "email": "star123best@gmail.com",\n' +
              '    "userID": 283880589279232,\n' +
              '    "username": "star123best"\n' +
              '}' },
          BAD_REQUEST_EXCEPTION,
          EMAIL_IN_USE_EXCEPTION,
          USERNAME_IN_USE_EXCEPTION,
          RATELIMIT_EXCEPTION,
          INTERNAL_SERVER_EXCEPTION
        ].sort((a, b) => a.code - b.code),
        rateLimit: 10,
        authenticated: false
      },
      {
        id: 'auth-login',
        path: '/login',
        title: 'Login',
        method: 'POST',
        description: 'Authenticate and receive a JWT.',
        bodyParams: [
          { name: 'email', type: 'string', description: 'Your email', exampleValue: 'star123best@gmail.com', required: true },
          { name: 'password', type: 'string', description: 'Your password', exampleValue: '##########', required: true}
        ],
        headers: [
          { name: 'X-Device-Id', type: 'uuid', description: 'Unique UUID for your device, generated by the browser', exampleValue: '288442c6-3f19-461c-a054-2b517dbf6837', required: true },
        ],
        responses: [
          { code: 200, title: 'Success', description: 'Successful login', exampleJson: '{\n' +
              '    "accessToken": "nuh uh not so fast",\n' +
              '    "createdAt": 1770677612,\n' +
              '    "displayName": "Star",\n' +
              '    "email": "star123best@gmail.com",\n' +
              '    "profilePicture": "https://someurl.com",\n' +
              '    "userID": 266190899122176,\n' +
              '    "username": "star123best"\n' +
              '}' },
          BAD_REQUEST_EXCEPTION,
          INVALID_CREDENTIALS_EXCEPTION,
          RATELIMIT_EXCEPTION,
          INTERNAL_SERVER_EXCEPTION
        ],
        rateLimit: 10,
        authenticated: false
      },
      {
        id: 'auth-logout',
        path: '/logout',
        title: 'Logout',
        method: 'POST',
        description: 'Log out of an account via a specific device-id.',
        responses: [
          { code: 200, title: 'Success', description: 'Successful logout', exampleJson: '{\n' +
              '    "data": null,\n' +
              '    "message": "Successful Logout",\n' +
              '    "status": 200,\n' +
              '    "timestamp": "2026-03-31T22:42:19.252440200Z"\n' +
              '}' },
          BAD_REQUEST_EXCEPTION,
          UNAUTHORIZED_EXCEPTION,
          INVALID_CREDENTIALS_EXCEPTION,
          NOT_FOUND_EXCEPTION,
          RATELIMIT_EXCEPTION,
          INTERNAL_SERVER_EXCEPTION
        ],
        headers: [
          AUTHORIZATION_HEADER,
          { name: 'X-Device-Id', type: 'uuid', description: 'Unique UUID for your device, generated by the browser', exampleValue: '288442c6-3f19-461c-a054-2b517dbf6837', required: true },
        ],
        rateLimit: 10,
        authenticated: true
      },
      {
        id: 'auth-logout-all',
        path: '/logoutAll',
        title: 'Logout all',
        method: 'POST',
        description: 'Log out of all sessions of an account irrespective of device.',
        headers: [
          AUTHORIZATION_HEADER
        ],
        responses: [
          { code: 200, title: 'Success', description: 'Successful logout', exampleJson: '{\n' +
              '    "data": null,\n' +
              '    "message": "Successful Logout",\n' +
              '    "status": 200,\n' +
              '    "timestamp": "2026-03-31T22:42:19.252440200Z"\n' +
              '}' },
          BAD_REQUEST_EXCEPTION,
          UNAUTHORIZED_EXCEPTION,
          INVALID_CREDENTIALS_EXCEPTION,
          NOT_FOUND_EXCEPTION,
          RATELIMIT_EXCEPTION,
          INTERNAL_SERVER_EXCEPTION
        ],
        rateLimit: 10,
        authenticated: true
      },
      {
        id: 'auth-refresh-token',
        path: '/refresh',
        title: 'Refresh Token',
        method: 'POST',
        description: 'Refreshes the access token via a refresh token (see Authentication help tab for more).',
        headers: [
          { name: 'Cookie', type: 'string', description: 'Your refresh token, passed via "refreshToken=..."', exampleValue: 'refreshToken=notsofastpartner', required: true },
        ],
        responses: [
          { code: 200, title: 'Success', description: 'Successful logout', exampleJson: '{\n' +
              '    "createdAt": 1774997415,\n' +
              '    "expiresAt": 1774998315,\n' +
              '    "token": "wouldn\'t you like to know weather boy"\n' +
              '}' },
          BAD_REQUEST_EXCEPTION,
          UNAUTHORIZED_EXCEPTION,
          INVALID_CREDENTIALS_EXCEPTION,
          NOT_FOUND_EXCEPTION,
          RATELIMIT_EXCEPTION,
          INTERNAL_SERVER_EXCEPTION
        ],
        rateLimit: 10,
        authenticated: true
      },
      {
        id: 'auth-delete-account',
        path: '/:id',
        title: 'Delete Account',
        method: 'DELETE',
        description: 'Deletes an account, no second chances (sorry little timmy)',
        headers: [
          AUTHORIZATION_HEADER
        ],
        parameters: [
          { name: 'id', type: 'string', description: 'The id of the account', exampleValue: '266190899122176' },
        ],
        responses: [
          { code: 200, title: 'Success', description: 'Successful deletion', exampleJson: '{\n' +
              '    "data": null,\n' +
              '    "message": "Account deleted successfully",\n' +
              '    "status": 200,\n' +
              '    "timestamp": "2026-03-31T22:42:19.252440200Z"\n' +
              '}' },
          NOT_FOUND_EXCEPTION,
          ...Object.values(STANDARD_EXCEPTIONS)
        ].sort((a, b) => a.code - b.code),
        rateLimit: 10,
        authenticated: true
      }
    ]
  },
  // Channels
  {
    name: 'Channels',
    basePath: 'http://localhost:8080/api/v1/channels',
    description: 'Channels Endpoint',
    endpoints : [
      {
        id: 'channel-get-data',
        path: '/:id',
        title: 'Get Channel Data',
        method: 'GET',
        description: 'Get the data for a specific channel',
        headers: [
          AUTHORIZATION_HEADER
        ],
        parameters: [
          { name: 'id', type: 'string', description: 'The id of the channel', exampleValue: '279273641291776' },
        ],
        responses: [
          { code: 200, title: 'Success', description: 'Channel data retrieved', exampleJson: '{\n' +
              '    "channelID": 279273641291776,\n' +
              '    "channelType": "GROUP",\n' +
              '    "createdAt": "2026-03-18T22:07:21.331800Z",\n' +
              '    "creatorID": 266190899122176,\n' +
              '    "image": "https://someUrl.com",\n' +
              '    "members": [\n' +
              '        266373788000256,\n' +
              '        266190899122176,\n' +
              '        266772090200064,\n' +
              '        276635052175360\n' +
              '    ],\n' +
              '    "name": "Groupchat"\n' +
              '}' },
          ...Object.values(STANDARD_EXCEPTIONS),
          NOT_FOUND_EXCEPTION,
        ].sort((a, b) => a.code - b.code),
        rateLimit: 50,
      },
      {
        id: 'channel-create',
        path: '/create',
        title: 'Create Channel',
        method: 'POST',
        description: 'Create a new channel',
        headers: [
          AUTHORIZATION_HEADER
        ],
        bodyParams: [
          { name: 'name', type: 'string', description: 'The name of the channel (Not to be used in DMS)', exampleValue: 'Random group chat', required: false },
          { name: 'channelType', type: 'string', description: 'ChannelType enum', exampleValue: 'DM', required: true},
          { name: 'members', type: 'object', description: 'List of members ids', exampleValue: '[266373788000256]', required: false}
        ],
        responses: [
          { code: 200, title: 'Success', description: 'New Channel Created', exampleJson: '{\n' +
              '    "channelID": 284043489480704,\n' +
              '    "channelType": "DM",\n' +
              '    "createdAt": "2026-04-01T09:35:55.049509700Z",\n' +
              '    "creatorID": 266190899122176,\n' +
              '    "image": null,\n' +
              '    "members": [\n' +
              '        266373788000256,\n' +
              '        266190899122176\n' +
              '    ],\n' +
              '    "name": null\n' +
              '}' },
          ...Object.values(STANDARD_EXCEPTIONS),
        ],
        rateLimit: 10,
      },
      {
        id: 'channel-delete',
        path: "/:id",
        title: 'Delete Channel',
        method: 'DELETE',
        description: 'Delete a channel',
        headers: [
          AUTHORIZATION_HEADER
        ],
        parameters: [
          { name: 'id', type: 'string', description: 'The id of the channel', exampleValue: '279273641291776' },
        ],
        responses: [
          { code: 200, title: 'Success', description: 'Channel deleted successfully', exampleJson: '{\n' +
              '    "data": null,\n' +
              '    "message": "Channel deleted successfully",\n' +
              '    "status": 200,\n' +
              '    "timestamp": "2026-03-31T22:42:19.252440200Z"\n' +
              '}' },
          NOT_FOUND_EXCEPTION,
          ...Object.values(STANDARD_EXCEPTIONS)
        ].sort((a, b) => a.code - b.code),
        rateLimit: 20,
      },
      {
        id: 'channel-update',
        path: "/:id",
        title: 'Update Channel',
        method: 'PATCH',
        description: 'Update a channel',
        headers: [
          AUTHORIZATION_HEADER
        ],
        parameters: [
          { name: 'id', type: 'string', description: 'The id of the channel', exampleValue: '279273641291776' },
        ],
        responses: [
          { code: 200, title: 'Success', description: 'Channel updated successfully', exampleJson: '{"token": "xyz"}' },
          NOT_FOUND_EXCEPTION,
          ...Object.values(STANDARD_EXCEPTIONS)
        ].sort((a, b) => a.code - b.code),
        rateLimit: 20,
      },
      {
        id: 'channel-add-member',
        path: "/add",
        title: 'Add members',
        method: 'POST',
        description: 'Add members to a specific channel',
        headers: [
          AUTHORIZATION_HEADER
        ],
        bodyParams: [
          { name: 'channelId', type: 'string', description: 'The id of the channel', exampleValue: '279273641291776' },
          { name: 'members', type: 'array', description: 'List of members ids', exampleValue: '[266373788000256]' },
        ],
        responses: [
          { code: 200, title: 'Success', description: 'Successfully added user', exampleJson: '{\n' +
              '    "data": null,\n' +
              '    "message": "Successfully added user",\n' +
              '    "status": 200,\n' +
              '    "timestamp": "2026-04-01T09:45:01.510491700Z"\n' +
              '}' },
          NOT_FOUND_EXCEPTION,
          ...Object.values(STANDARD_EXCEPTIONS)
        ].sort((a, b) => a.code - b.code),
        rateLimit: 20,
      },
      {
        id: 'channel-get-all',
        path: "/getAll",
        title: 'Get All Conversations',
        method: 'GET',
        description: 'Get all conversations (chats and channels)',
        headers: [
          AUTHORIZATION_HEADER
        ],
        responses: [
          { code: 200, title: 'Success', description: 'Successfully retrieved conversations', exampleJson: '{\n' +
              '    "channels": [\n' +
              '        {\n' +
              '            "channelID": 284043489480704,\n' +
              '            "channelType": "DM",\n' +
              '            "createdAt": "2026-04-01T09:35:55.049510Z",\n' +
              '            "creatorID": 266190899122176,\n' +
              '            "image": null,\n' +
              '            "members": [\n' +
              '                266373788000256,\n' +
              '                266190899122176\n' +
              '            ],\n' +
              '            "name": null\n' +
              '        }' +
              '    ],\n' +
              '    "timestamp": "2026-04-01T09:50:17.032115200Z"\n' +
              '}'},
          UNAUTHORIZED_EXCEPTION,
          RATELIMIT_EXCEPTION,
          INTERNAL_SERVER_EXCEPTION
        ].sort((a, b) => a.code - b.code),
        rateLimit: 10,
      },
      {
        id: 'channel-get-chats',
        path: "/getAll/chats",
        title: 'Get All Chats',
        method: 'GET',
        description: 'Get all chats for a user',
        headers: [
          AUTHORIZATION_HEADER
        ],
        responses: [
          { code: 200, title: 'Success', description: 'Successfully retrieved chats', exampleJson: '{\n' +
              '    "channels": [\n' +
              '        {\n' +
              '            "channelID": 284043489480704,\n' +
              '            "channelType": "DM",\n' +
              '            "createdAt": "2026-04-01T09:35:55.049510Z",\n' +
              '            "creatorID": 266190899122176,\n' +
              '            "image": null,\n' +
              '            "members": [\n' +
              '                266373788000256,\n' +
              '                266190899122176\n' +
              '            ],\n' +
              '            "name": null\n' +
              '        }' +
              '    ],\n' +
              '    "timestamp": "2026-04-01T09:50:17.032115200Z"\n' +
              '}'},
          UNAUTHORIZED_EXCEPTION,
          RATELIMIT_EXCEPTION,
          INTERNAL_SERVER_EXCEPTION
        ].sort((a, b) => a.code - b.code),
        rateLimit: 10,
      },
      {
        id: 'channel-get-channels',
        path: "/getAll/channels",
        title: 'Get All Channels',
        method: 'GET',
        description: 'Get all channels for a user',
        headers: [
          AUTHORIZATION_HEADER
        ],
        responses: [
          { code: 200, title: 'Success', description: 'Successfully retrieved channels', exampleJson: '{\n' +
              '    "channels": [\n' +
              '        {\n' +
              '            "channelID": 284043489480704,\n' +
              '            "channelType": "CHANNEL",\n' +
              '            "createdAt": "2026-04-01T09:35:55.049510Z",\n' +
              '            "creatorID": 266190899122176,\n' +
              '            "name": null\n' +
              '        }' +
              '    ],\n' +
              '    "timestamp": "2026-04-01T09:50:17.032115200Z"\n' +
              '}'},
          UNAUTHORIZED_EXCEPTION,
          RATELIMIT_EXCEPTION,
          INTERNAL_SERVER_EXCEPTION
        ].sort((a, b) => a.code - b.code),
        rateLimit: 20,
      }
    ]
  },
  // Messages
  {
    name: 'Messages',
    basePath: 'http://localhost:8080/api/v1/messages',
    description: 'Messages Endpoint',
    endpoints : [
      {
        id: 'message-get',
        path: '/:id',
        title: 'Get Messages',
        method: 'GET',
        description: 'Get messages in a specific channel, where :id is the channel Id\n\nNote: tempId is a value used for the "pre-sending" feature, more information on that is in the web-sockets section, and should NOT be used outside of web sockets',
        headers: [
          AUTHORIZATION_HEADER
        ],
        responses: [
          { code: 200, title: 'Success', description: 'Messages retrieved', exampleJson: '{\n' +
              '    "channelID": 280903007481856,\n' +
              '    "messages": [\n' +
              '        {\n' +
              '            "authorID": 266190899122176,\n' +
              '            "channelID": 280903007481856,\n' +
              '            "content": "if you\'re reading this, you\'re cool beans",\n' +
              '            "messageID": 281609683959808,\n' +
              '            "tempId": null,\n' +
              '            "timestamp": "2026-03-25T12:32:44.248529Z"\n' +
              '        }\n' +
              '    ],\n' +
              '    "timestamp": 1775029188\n' +
              '}' },
          NOT_FOUND_EXCEPTION,
          ...Object.values(STANDARD_EXCEPTIONS)
        ].sort((a, b) => a.code - b.code),
        rateLimit: 100,
      },
      {
        id: 'message-get-history',
        path: '/history/:id',
        title: 'Get Message History',
        method: 'GET',
        description: 'Get messages in a specific channel, where :id is the channel Id, with specific parameters\n\nNote: tempId is a value used for the "pre-sending" feature, more information on that is in the web-sockets section. tempId should NOT be used outside of web sockets',
        parameters: [
          { name: 'id', type: 'number', description: 'The channel id to get history for', exampleValue: 280903007481856, required: true },
          { name: 'page', type: 'number', description: 'Query parameter for the index of the page, used for pagination (start from 0)', exampleValue: 0 },
          { name: 'size', type: 'number', description: 'Query parameter for the maximum number of messages that can be returned in one page', exampleValue: 100 },
          { name: 'ascending', type: 'number', description: 'Query parameter, set to true if the result should be sorted ascending (old -> new), and false if descending (new -> old)', exampleValue: true },
          { name: 'after', type: 'number', description: 'Query parameter for the unix timestamp the messages should be sent after', exampleValue: 1771162177 },
          { name: 'before', type: 'number', description: 'Query parameter for the unix timestamp the messages should be sent before', exampleValue: 1771252177 },
        ],
        headers: [
          AUTHORIZATION_HEADER
        ],
        responses: [
          { code: 200, title: 'Success', description: 'Message history retrieved', exampleJson: '{\n' +
              '    "channelID": 280903007481856,\n' +
              '    "messages": [\n' +
              '        {\n' +
              '            "authorID": 266190899122176,\n' +
              '            "channelID": 280903007481856,\n' +
              '            "content": "if you\'re reading this, you\'re extra cool beans",\n' +
              '            "messageID": 281609683959808,\n' +
              '            "tempId": null,\n' +
              '            "timestamp": "2026-03-25T12:32:44.248529Z"\n' +
              '        }\n' +
              '    ],\n' +
              '    "timestamp": 1775029188\n' +
              '}' },
          NOT_FOUND_EXCEPTION,
          ...Object.values(STANDARD_EXCEPTIONS)
        ].sort((a, b) => a.code - b.code),
        rateLimit: 100,
      },
    ]
  },
  // Users
  {
    name: 'Users',
    basePath: 'http://localhost:8080/api/v1/users',
    description: 'Users Endpoint',
    endpoints : [
      {
        id: 'get-user',
        path: '/:id',
        title: 'Get User',
        method: 'GET',
        description: 'Get a user\'s information',
        headers: [
          AUTHORIZATION_HEADER
        ],
        parameters: [
          { name: 'id', type: 'number', description: 'The id of the user you wish to get the information for' },
        ],
        responses: [
          { code: 200, title: 'Success', description: 'User information retrieved', exampleJson: '{\n' +
              '    "createdAt": 1770677612,\n' +
              '    "displayName": "Star",\n' +
              '    "presence": "ONLINE",\n' +
              '    "profilePicture": "https://someApi.com",\n' +
              '    "userID": 266190899122176,\n' +
              '    "username": "star123best"\n' +
              '}' },
          BAD_REQUEST_EXCEPTION,
          UNAUTHORIZED_EXCEPTION,
          NOT_FOUND_EXCEPTION,
          RATELIMIT_EXCEPTION,
          INTERNAL_SERVER_EXCEPTION,
        ],
        rateLimit: 50,
        authenticated: true,
      },
      {
        id: 'get-multiple-users',
        path: '/get',
        title: 'Get Multiple Users',
        method: 'POST',
        description: 'Get multiple user\'s information \n\nNote: The request method is set to POST to allow a request body, this is the only way I could have done it',
        headers: [
          AUTHORIZATION_HEADER
        ],
        bodyParams: [
          { name: 'users', type: 'array', description: 'A list of the ids of the users you wish to get the presence for', exampleValue: '[266190899122176, 266373788000256, 266772090200064]', required: true },
        ],
        responses: [
          { code: 200, title: 'Success', description: 'User presence retrieved', exampleJson: '{\n' +
              '    "userId": 266190899122176,\n' +
              '    "presence": "ONLINE"\n' +
              '}' },
          BAD_REQUEST_EXCEPTION,
          UNAUTHORIZED_EXCEPTION,
          NOT_FOUND_EXCEPTION,
          RATELIMIT_EXCEPTION,
          INTERNAL_SERVER_EXCEPTION,
        ],
        rateLimit: 30,
        authenticated: true,
      },
      {
        id: 'get-presence',
        path: '/:id/presence',
        title: 'Get Presence',
        method: 'GET',
        description: 'Get a users presence',
        headers: [
          AUTHORIZATION_HEADER
        ],
        parameters: [
          { name: 'id', type: 'number', description: 'The id of the user you wish to get the presence for' },
        ],
        responses: [
          { code: 200, title: 'Success', description: 'User presence retrieved', exampleJson: '{\n' +
              '    "userId": 266190899122176,\n' +
              '    "presence": "ONLINE"\n' +
              '}' },
          BAD_REQUEST_EXCEPTION,
          UNAUTHORIZED_EXCEPTION,
          NOT_FOUND_EXCEPTION,
          RATELIMIT_EXCEPTION,
          INTERNAL_SERVER_EXCEPTION,
        ],
        rateLimit: 30,
        authenticated: true,
      },
      {
        id: 'update-presence',
        path: '/:id/presence',
        title: 'Update Presence',
        method: 'PATCH',
        description: 'Update the presence for a specific user',
        headers: [
          AUTHORIZATION_HEADER
        ],
        bodyParams: [
          { name: 'presence', type: 'string', description: 'The new presence for the user (ONLINE, IDLE, DND, INVISIBLE)',  exampleValue: "ONLINE", required: true },
        ],
        responses: [
          { code: 200, title: 'Success', description: 'Presence updated successfully', exampleJson: '{\n' +
              '    "data": null,\n' +
              '    "message": "Successfully updated presence to ONLINE",\n' +
              '    "status": 200,\n' +
              '    "timestamp": "2026-04-01T11:08:52.791152500Z"\n' +
              '}' },
          ...Object.values(STANDARD_EXCEPTIONS),
          NOT_FOUND_EXCEPTION
        ].sort((a, b) => a.code - b.code),
        rateLimit: 30,
        authenticated: true,
      },
    ]
  },
  // Web sockets
  {
    name: 'Web sockets',
    basePath: 'ws://localhost:8080',
    description: 'All the websockets used in Starcord',
    endpoints : [
      {
        id: 'ws-connect',
        path: '/ws',
        title: 'Connect',
        method: 'WS',
        description: 'Connect to the websocket\n\nNote: user-name is actually your user id, due to Spring websocket limitations I had to use this convention',
        headers: [
          AUTHORIZATION_HEADER
        ],
        responses: [
          { code: 200, title: 'Success', description: 'Connected successfully', exampleJson: '10:32:47 - STOMP: <<< CONNECTED\n' +
              'user-name:266190899122176\n' +
              'heart-beat:0,0\n' +
              'version:1.2\n' +
              'content-length:0' },
          ...Object.values(STANDARD_EXCEPTIONS)
        ],
        rateLimit: 20,
      },
      {
        id: 'ws-send-gc',
        path: '/app/group/:id',
        title: 'Send to GC',
        method: 'WS',
        description: 'Send a message to a group chat',
        headers: [
          AUTHORIZATION_HEADER
        ],
        responses: [
          { code: 200, title: 'Success', description: 'Message sent successfully', exampleJson: '10:43:32 - STOMP: >>> SEND\n' +
              'destination:/app/group/279273641291776\n' +
              'content-length:86' },
          ...Object.values(STANDARD_EXCEPTIONS)
        ],
        rateLimit: 20,
      },
      {
        id: 'ws-listen-gc',
        path: '/app/group/:id',
        title: 'Listen to GC',
        method: 'WS',
        description: 'Listed to messages from a group chat',
        headers: [
          AUTHORIZATION_HEADER
        ],
        responses: [
          { code: 200, title: 'Success', description: 'Listening connection established', exampleJson: '10:47:39 - STOMP: >>> SUBSCRIBE\n' +
              'id:sub-1\n' +
              'destination:/topic/group.groupId' },
          ...Object.values(STANDARD_EXCEPTIONS)
        ],
        rateLimit: 20,
      },
      {
        id: 'ws-send-dm',
        path: '/app/chat.private',
        title: 'Send Private DM',
        method: 'WS',
        description: 'Send a private message to a specific user via a DM channel',
        headers: [
          AUTHORIZATION_HEADER
        ],
        responses: [
          {
            code: 200,
            title: 'Success',
            description: 'Message sent to the message broker',
            exampleJson: '11:05:12 - STOMP: >>> SEND\n' +
              'destination:/app/chat.private\n' +
              'content-type:application/json\n' +
              '\n' +
              '{"channelId": "280903007481856", "content": "hi cool person", "tempId": "dfb73345-d2b7-4b9f-840c-f4da376a8508"}'
          },
          ...Object.values(STANDARD_EXCEPTIONS)
        ],
        rateLimit: 20,
      },
      {
        id: 'ws-receive-dm',
        path: '/user/queue/messages',
        title: 'Receive Private DM',
        method: 'WS',
        description: 'The STOMP frame received when another user sends a message to your private queue',
        headers: [
          AUTHORIZATION_HEADER
        ],
        responses: [
          {
            code: 200,
            title: 'Success',
            description: 'Incoming message payload',
            exampleJson: '11:29:56 - STOMP: <<< MESSAGE\n' +
              'content-length:341\n' +
              'message-id:628d11e0-889a-0dd1-1d0a-ea9e042f8ab6-6\n' +
              'subscription:sub-1\n' +
              'content-type:application/json\n' +
              'destination:/user/queue/messages\n' +
              '\n' +
              '{"messageID": 281609683959808, "authorID": 266190899122176, "content": "why hello there", "channelID": 555, "timestamp": "2024-05-20T12:00:00Z"}'
          },
          ...Object.values(STANDARD_EXCEPTIONS)
        ],
        rateLimit: 20,
      },
      {
        id: 'ws-receive-dm-receipt',
        path: '/user/queue/reply',
        title: 'Receive DM Receipt',
        method: 'WS',
        description: 'The STOMP frame received after you send a DM, confirming the server processed it',
        headers: [
          AUTHORIZATION_HEADER
        ],
        responses: [
          {
            code: 200,
            title: 'Success',
            description: 'SuccessResponse payload',
            exampleJson: '11:29:56 - STOMP: <<< MESSAGE\n' +
              'content-length:341\n' +
              'message-id:628d11e0-889a-0dd1-1d0a-ea9e042f8ab6-6\n' +
              'subscription:sub-1\n' +
              'content-type:application/json\n' +
              'destination:/user/queue/reply\n' +
              '\n' +
              '{"success": true, "message": "HALLOOOOO", "tempId": "dfb73345-d2b7-4b9f-840c-f4da376a8508", "messageId": 281609683959808}'
          },
          ...Object.values(STANDARD_EXCEPTIONS)
        ],
        rateLimit: 20,
      }
    ]
  }
];
